name: Build for Chrome

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install codecov
        run: npm install -g codecov
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run release-chrome
      - name: Upload Build as Artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist-chrome
          path: dist-chrome
